import type { Tables, TablesInsert } from "./db/database.types";

// =================================================================
// GENERIC API RESPONSE TYPES
// =================================================================

/**
 * Represents the metadata for paginated API responses.
 */
export interface PaginationDto {
  page: number;
  limit: number;
  total_items: number;
  total_pages: number;
}

/**
 * A generic wrapper for successful API responses.
 * @template T The type of the data payload.
 */
export interface ApiSuccessResponse<T> {
  data: T;
  pagination?: PaginationDto;
}

/**
 * A generic wrapper for error API responses.
 */
export interface ApiErrorResponse {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
}

// =================================================================
// FLASHCARD TYPES
// =================================================================

/**
 * Data Transfer Object for a flashcard.
 * Directly maps to the `flashcards` table schema.
 */
export type FlashcardDto = Tables<"flashcards">;

/**
 * DTO for a paginated list of flashcards.
 */
export interface PaginatedFlashcardsDto {
  data: FlashcardDto[];
  pagination: PaginationDto;
}

/**
 * Represents a single flashcard object within the `CreateFlashcardsCommand`.
 * This type includes only the fields required from the client for creation.
 */
export type FlashcardToCreate = Pick<TablesInsert<"flashcards">, "front" | "back" | "source">;

/**
 * Command model for creating one or more flashcards.
 * Used in `POST /api/flashcards`.
 */
export interface CreateFlashcardsCommand {
  generation_id?: number;
  flashcards: FlashcardToCreate[];
}

/**
 * DTO for the result of a successful flashcard creation operation.
 */
export interface CreateFlashcardsResultDto {
  created_count: number;
  flashcards: FlashcardDto[];
}

/**
 * Command model for updating a flashcard.
 * All fields are optional. Used in `PATCH /api/flashcards/:id`.
 */
export type UpdateFlashcardCommand = Partial<Pick<FlashcardDto, "front" | "back">>;

// =================================================================
// GENERATION TYPES
// =================================================================

/**
 * Data Transfer Object for an AI generation event.
 * Directly maps to the `generations` table schema.
 */
export type GenerationDto = Tables<"generations">;

/**
 * DTO for a paginated list of generation events.
 */
export interface PaginatedGenerationsDto {
  data: GenerationDto[];
  pagination: PaginationDto;
}

/**
 * Command model for initiating an AI flashcard generation.
 * Used in `POST /api/generations`.
 */
export interface GenerateFlashcardsCommand {
  source_text: string;
}

/**
 * Represents a flashcard candidate generated by the AI, before it is saved.
 * It does not have an ID or other database-managed fields yet.
 */
export type FlashcardCandidateDto = Pick<FlashcardDto, "front" | "back">;

/**
 * DTO for the result of a successful AI generation request.
 * Contains metadata about the generation event and the candidate flashcards.
 */
export type GenerateFlashcardsResultDto = Pick<
  GenerationDto,
  "model" | "generated_count" | "generation_duration" | "created_at"
> & {
  /**
   * The ID of the generation event, to be used when saving the flashcards.
   * Renamed from `id` for clarity.
   */
  generation_id: GenerationDto["id"];
  flashcard_candidates: FlashcardCandidateDto[];
};

// End of file
