/*
 * Migration: Create Flashcards Schema
 * Created: 2025-12-28
 * 
 * Purpose:
 *   Sets up the complete database schema for the 10xdevs-flashcards application.
 *   This migration creates tables for flashcards, AI generation tracking, and error logging.
 * 
 * Affected Tables:
 *   - flashcards: stores user-created flashcard content
 *   - generations: logs successful AI generation events
 *   - generation_error_logs: tracks failed AI generation attempts
 * 
 * Special Considerations:
 *   - All tables have Row Level Security (RLS) enabled
 *   - Users can only access their own data (auth.uid() = user_id)
 *   - Triggers automatically maintain updated_at timestamps
 *   - Full-text search index on flashcards for efficient searching
 */

-- ==============================================================================
-- 1. Create Tables
-- ==============================================================================

-- -----------------------------------------------------------------------------
-- Table: generations
-- Purpose: Logs metadata for each successful AI flashcard generation event
-- Note: Created first as it's the parent table referenced by flashcards
-- -----------------------------------------------------------------------------
create table if not exists public.generations (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model varchar not null,
  generated_count integer not null,
  accepted_unedited_count integer null,
  accepted_edited_count integer null,
  source_text_hash varchar not null,
  source_text_length integer not null check (source_text_length between 1000 and 10000),
  generation_duration integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add comments for generations table
comment on table public.generations is 'Logs metadata for each successful AI flashcard generation event';
comment on column public.generations.id is 'Unique identifier for the generation event';
comment on column public.generations.user_id is 'The user who initiated the generation';
comment on column public.generations.model is 'The AI model used for generation (e.g., gpt-4, claude-3)';
comment on column public.generations.generated_count is 'The number of flashcard candidates generated by the AI';
comment on column public.generations.accepted_unedited_count is 'The number of candidates the user accepted as-is';
comment on column public.generations.accepted_edited_count is 'The number of candidates the user accepted after editing';
comment on column public.generations.source_text_hash is 'SHA-256 hash of the source text for deduplication';
comment on column public.generations.source_text_length is 'Length of the source text (must be between 1000-10000 chars)';
comment on column public.generations.generation_duration is 'The duration of the generation process in milliseconds';
comment on column public.generations.created_at is 'Timestamp when the generation event occurred';
comment on column public.generations.updated_at is 'Timestamp when the generation log was last updated (auto-maintained by trigger)';

-- -----------------------------------------------------------------------------
-- Table: flashcards
-- Purpose: Stores the content for each flashcard created by a user
-- Note: Created after generations table to allow direct FK constraint definition
-- -----------------------------------------------------------------------------
create table if not exists public.flashcards (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  generation_id bigint null references public.generations(id) on delete set null,
  front varchar(200) not null,
  back varchar(500) not null,
  source varchar not null check (source in ('ai-full', 'ai-edited', 'manual')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add comment for flashcards table
comment on table public.flashcards is 'Stores flashcard content created by users through AI generation or manual input';
comment on column public.flashcards.id is 'Unique identifier for the flashcard';
comment on column public.flashcards.user_id is 'The user who owns the flashcard';
comment on column public.flashcards.generation_id is 'The AI generation event that created the card (nullable)';
comment on column public.flashcards.front is 'The front content of the flashcard (max 200 chars)';
comment on column public.flashcards.back is 'The back content of the flashcard (max 500 chars)';
comment on column public.flashcards.source is 'Origin of the flashcard: ai-full (unedited AI), ai-edited (modified AI), or manual';
comment on column public.flashcards.created_at is 'Timestamp when the flashcard was created';
comment on column public.flashcards.updated_at is 'Timestamp when the flashcard was last updated (auto-maintained by trigger)';

-- -----------------------------------------------------------------------------
-- Table: generation_error_logs
-- Purpose: Logs details of failed AI generation attempts
-- -----------------------------------------------------------------------------
create table if not exists public.generation_error_logs (
  id bigserial primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  model varchar not null,
  source_text_hash varchar not null,
  source_text_length integer not null check (source_text_length between 1000 and 10000),
  error_code varchar(100) not null,
  error_message text not null,
  created_at timestamptz not null default now()
);

-- Add comments for generation_error_logs table
comment on table public.generation_error_logs is 'Logs details of failed AI generation attempts for debugging and monitoring';
comment on column public.generation_error_logs.id is 'Unique identifier for the error log entry';
comment on column public.generation_error_logs.user_id is 'The user who experienced the error';
comment on column public.generation_error_logs.model is 'The AI model used for generation';
comment on column public.generation_error_logs.source_text_hash is 'SHA-256 hash of the source text';
comment on column public.generation_error_logs.source_text_length is 'Length of the source text (must be between 1000-10000 chars)';
comment on column public.generation_error_logs.error_code is 'A code identifying the type of error (e.g., RATE_LIMIT, INVALID_INPUT)';
comment on column public.generation_error_logs.error_message is 'The error message or reason for the failure';
comment on column public.generation_error_logs.created_at is 'Timestamp when the error occurred';

-- ==============================================================================
-- 2. Create Indexes
-- ==============================================================================

-- -----------------------------------------------------------------------------
-- Indexes for generations table
-- Purpose: Optimize queries filtering by user_id
-- -----------------------------------------------------------------------------
create index if not exists generations_user_id_idx on public.generations(user_id);

-- -----------------------------------------------------------------------------
-- Indexes for flashcards table
-- Purpose: Optimize queries filtering by user_id, generation_id, and full-text search
-- -----------------------------------------------------------------------------
create index if not exists flashcards_user_id_idx on public.flashcards(user_id);
create index if not exists flashcards_generation_id_idx on public.flashcards(generation_id);

-- Full-text search index using GIN (Generalized Inverted Index)
-- This enables efficient searching across both front and back card content
create index if not exists flashcards_full_text_idx on public.flashcards using gin(to_tsvector('english', front || ' ' || back));

-- Add comment for full-text search index
comment on index public.flashcards_full_text_idx is 'GIN index for efficient full-text search across flashcard front and back content';

-- -----------------------------------------------------------------------------
-- Indexes for generation_error_logs table
-- Purpose: Optimize queries filtering by user_id
-- -----------------------------------------------------------------------------
create index if not exists generation_error_logs_user_id_idx on public.generation_error_logs(user_id);

-- ==============================================================================
-- 3. Create Triggers
-- ==============================================================================

-- -----------------------------------------------------------------------------
-- Function: handle_updated_at
-- Purpose: Generic trigger function to automatically update the updated_at column
-- -----------------------------------------------------------------------------
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Add comment for trigger function
comment on function public.handle_updated_at is 'Trigger function that automatically updates the updated_at column to the current timestamp';

-- -----------------------------------------------------------------------------
-- Trigger: generations_updated_at_trigger
-- Purpose: Automatically maintain the updated_at timestamp on generations table
-- -----------------------------------------------------------------------------
create trigger generations_updated_at_trigger
  before update on public.generations
  for each row
  execute function public.handle_updated_at();

-- -----------------------------------------------------------------------------
-- Trigger: flashcards_updated_at_trigger
-- Purpose: Automatically maintain the updated_at timestamp on flashcards table
-- -----------------------------------------------------------------------------
create trigger flashcards_updated_at_trigger
  before update on public.flashcards
  for each row
  execute function public.handle_updated_at();

-- ==============================================================================
-- 4. Enable Row Level Security (RLS)
-- ==============================================================================

-- Enable RLS on all tables
-- This ensures that users can only access their own data
alter table public.flashcards enable row level security;
alter table public.generations enable row level security;
alter table public.generation_error_logs enable row level security;

-- ==============================================================================
-- 5. Create RLS Policies
-- ==============================================================================

-- -----------------------------------------------------------------------------
-- RLS Policies for generations table
-- Purpose: Users can only access their own generation logs
-- -----------------------------------------------------------------------------

-- Policy: Allow authenticated users to SELECT their own generation logs
create policy "generations_select_policy_authenticated"
  on public.generations
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Allow authenticated users to INSERT their own generation logs
create policy "generations_insert_policy_authenticated"
  on public.generations
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to UPDATE their own generation logs
create policy "generations_update_policy_authenticated"
  on public.generations
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to DELETE their own generation logs
create policy "generations_delete_policy_authenticated"
  on public.generations
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- RLS Policies for flashcards table
-- Purpose: Users can only access their own flashcards
-- -----------------------------------------------------------------------------

-- Policy: Allow authenticated users to SELECT their own flashcards
create policy "flashcards_select_policy_authenticated"
  on public.flashcards
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Allow authenticated users to INSERT their own flashcards
create policy "flashcards_insert_policy_authenticated"
  on public.flashcards
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to UPDATE their own flashcards
create policy "flashcards_update_policy_authenticated"
  on public.flashcards
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to DELETE their own flashcards
create policy "flashcards_delete_policy_authenticated"
  on public.flashcards
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- RLS Policies for generation_error_logs table
-- Purpose: Users can only access their own error logs
-- -----------------------------------------------------------------------------

-- Policy: Allow authenticated users to SELECT their own error logs
create policy "generation_error_logs_select_policy_authenticated"
  on public.generation_error_logs
  for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Allow authenticated users to INSERT their own error logs
create policy "generation_error_logs_insert_policy_authenticated"
  on public.generation_error_logs
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to UPDATE their own error logs
create policy "generation_error_logs_update_policy_authenticated"
  on public.generation_error_logs
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Policy: Allow authenticated users to DELETE their own error logs
create policy "generation_error_logs_delete_policy_authenticated"
  on public.generation_error_logs
  for delete
  to authenticated
  using (auth.uid() = user_id);

